import 'package:hive/hive.dart';

part 'user_model.g.dart';
// This file is auto-generated by Hive's build_runner.
// It contains the adapter code required for serialization/deserialization.

/// UserModel:
/// Represents a single user in the app.
/// Stored inside Hive local database.
/// Extends HiveObject → so it can use helper methods like `.save()`, `.delete()`.
@HiveType(typeId: 1) // Unique typeId for this model (must not clash with other models)
class UserModel extends HiveObject {
  @HiveField(0)
  String id; // Unique identifier for the user (can be UUID or email)

  @HiveField(1)
  String name; // Display name of the user

  @HiveField(2)
  String email; // User's email address (used for login)

  @HiveField(3)
  String password; // User's password (⚠ stored in plain text in Hive;
  // in production use hashing for security!)

  /// Constructor to create a new UserModel object
  UserModel({
    required this.id,
    required this.name,
    required this.email,
    required this.password,
  });
}
