import 'package:hive/hive.dart';

part 'video_model.g.dart';
// This file is generated by Hive's build_runner.
// It contains the adapter for serializing/deserializing this model into Hive boxes.

/// VideoModel:
/// Represents a single video item stored in Hive database.
/// Extends HiveObject → gives you `.save()` and `.delete()` helpers.
@HiveType(typeId: 0) // Unique typeId (must be different from other Hive models)
class VideoModel extends HiveObject {
  @HiveField(0)
  String id;
  // Unique identifier for the video (usually generated with UUID).

  @HiveField(1)
  String url;
  // Video source URL or local file path.
  // - If network video → a playable link (e.g., from Pexels API or Google Drive).
  // - If local video → path returned by FilePicker.

  @HiveField(2)
  int likes;
  // Total count of likes this video has received.

  @HiveField(3)
  List<String> likedBy;
  // List of user IDs who liked this video.
  // Used to prevent multiple likes from the same user and to allow toggling (like/dislike).

  @HiveField(4)
  List<String> viewers;
  // List of user IDs who have viewed this video.
  // Useful for showing "viewers list" in bottom sheet.

  /// Constructor:
  /// - Initializes with 0 likes and empty lists if not provided.
  VideoModel({
    required this.id,
    required this.url,
    this.likes = 0,
    List<String>? likedBy,
    List<String>? viewers,
  })  : likedBy = likedBy ?? [],
        viewers = viewers ?? [];
}
